version: 0.2
phases:
  install:
    commands:
      - echo 'Nothing To Install'
  pre_build:
    commands:
      - echo 'Nothing To Do In Pre-Build Phase'
      - $(aws ecr get-login --no-include-email --region us-west-2)      
  build:
    commands:
      - echo '-----------------------------------------------------------------------------------------'
      - echo 'Building Custom Image For AWS Code Build'
      - echo '-----------------------------------------------------------------------------------------'
      - docker build --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -t aws-cicd-customimage:latest .
      - docker tag aws-cicd-customimage:latest 138871512076.dkr.ecr.us-west-2.amazonaws.com/pge-ecm-cicd-customimage:latest
      - echo '-----------------------------------------------------------------------------------------'
      - echo 'Bulding Docker Image And Tagging Completed Sucessfully'
      - echo '-----------------------------------------------------------------------------------------'
  post_build:
    commands:
      - echo '----------------------------------------------------------------------------------------'
      - echo 'Logging Into AWS ECR Repository pge-ecm-cicd-customimage'
      - echo '-----------------------------------------------------------------------------------------'
      - echo 'Pushing Custom Image To Repository pge-ecm-cicd-customimage'
      - echo '-----------------------------------------------------------------------------------------'
      - docker push 138871512076.dkr.ecr.us-west-2.amazonaws.com/pge-ecm-cicd-customimage:latest
